### Prueba 1: Inferencia de IA (Cliente con Riesgo Alto)
POST https://django-backend-ecosystem-ksn7.onrender.com/api/v1/predict/
Content-Type: application/json

{
  "frecuencia_compra": 2,
  "monto_promedio": 15000,
  "dias_ultima_compra": 45
}

###

### Prueba 2: Inferencia de IA (Cliente Activo / Bajo Riesgo)
POST https://django-backend-ecosystem-ksn7.onrender.com/api/v1/predict/
Content-Type: application/json

{
  "frecuencia_compra": 18,
  "monto_promedio": 180000.0,
  "dias_ultima_compra": 2
}
